# There is the fix for an issue: traefik                                       | 2025-03-25T23:53:48Z ERR github.com/traefik/traefik/v3/cmd/traefik/traefik.go:249 > Plugins are disabled because an error has occurred. error="failed to eval New: 1:28: undefined: swagger_merge_docs" plugins=["swagger-merge-docs"]